"""Second  migration

Revision ID: 8d1bed2bdfff
Revises: c133f59706c1
Create Date: 2025-02-13 18:27:33.183926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1bed2bdfff'
down_revision = 'c133f59706c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('visit_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('visit_time',
               existing_type=sa.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('visit_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('visit_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
